title: "On the Radar"
email: csisideaslab@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The website for the On the Radar study by the CSIS Project on Nuclear Issues (PONI) program.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:

date_format: '%B %-d, %Y'

cloudinary_url: https://res.cloudinary.com/csisideaslab/image/upload/

# Content types will be defined here
collections:
  posts:
    title: Analysis
    output: true
  briefs:
    title: Issue Briefs
    output: true
  workshops:
    title: Workshops
    output: true
  resources:
    title: Resources
    output: false
  authors:
    title: Authors
    output: true

# Default front matter values for a collection will be defined here
defaults:
- scope:
    path: ''
    type: 'posts'
  values:
    layout: post
    permalink: "/analysis/:slug/"
    view_all_url: "/analysis/"
    breadcrumbs: true
- scope:
    path: ''
    type: 'briefs'
  values:
    layout: post
    permalink: "/issue-briefs/:slug/"
    view_all_url: "/issue-briefs/"
    breadcrumbs: true
- scope:
    path: ''
    type: 'workshops'
  values:
    layout: post
    permalink: "/workshops/:slug/"
    view_all_url: "/workshops/"
    breadcrumbs: true
- scope:
    path: ''
    type: 'authors'
  values:
    layout: archive
    permalink: "/authors/:slug/"
    breadcrumbs: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - frasco.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - INCLUDES.md
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - prettier.config.js
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
