title: "On the Radar"
email: csisideaslab@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The website for the On the Radar study by the CSIS Project on Nuclear Issues (PONI) program.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 

cloudinary_url: https://res.cloudinary.com/csisideaslab/image/upload/

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - frasco.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - INCLUDES.md
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - prettier.config.js
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
