---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: DATA
- type: document
  path: _data/categories.yml
  label: Categories
- type: document
  path: _data/glossary.yml
  label: Glossary
- type: document
  path: _data/issue_briefs.yml
  label: Issue Briefs
  match: "**/*"
- type: document
  path: _data/keywords.yml
  label: Keywords
  match: "**/*"
- type: document
  path: _data/language.yml
  label: Language
  match: "**/*"
upload_dir: on-the-radar
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
