---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-posts
  label: Analysis
  create: all
  templates:
  - posts
- type: directory
  path: _briefs
  label: Briefs
  create: all
  match: "**/*"
  templates:
  - briefs
- type: directory
  path: _workshops
  label: Workshops
  create: all
  match: "**/*"
  templates:
  - workshops
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resources
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - authors
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: DATA
- type: document
  path: _data/categories.yml
  label: Categories
- type: document
  path: _data/keywords.yml
  label: Keywords
- type: document
  path: _data/resources.yml
  label: Resources
- type: document
  path: _data/glossary.yml
  label: Glossary
- type: document
  path: _data/principle_researchers.yml
  label: About Page Researchers
- type: document
  path: _data/brief-tech.yml
  label: Tech Primer
- type: document
  path: _data/brief-countries.yml
  label: Country Brief
- type: document
  path: _data/language.yml
  label: Language
upload_dir: on-the-radar
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
